### PR TITLE
please delete this

### PR DESCRIPTION
**Pull request by SabineMa**
afaik this is not needed.
also I moved the .properties file to the subdirectory where the code is (saw this in other repositories)
with this changes it seems to work

(this is my first pull request, hope everything ok like this)

### CODE REVIEW

**Comment by SabineMa** [comment]
can you please tag it after merging?

**Comment by hernanmd** [comment]
Hi Sabine,

Can you check this change?

https://github.com/hernanmd/FixedDecimal/pull/3/commits/d7775e7061369baf91861831958d21087bbc0357

Because I think that would redirect the installation script to your fork (in the README.md of this repo).

**Comment by SabineMa** [comment]
Hi Hernan,
 this works with a fresh pharo6.1 image:
```
Metacello new
	repository: 'github://hernanmd/FixedDecimal/repository';	
	baseline: 'FixedDecimal';
	load.
```
and this works, too in another fresh pharo 6.1 image:
```
Metacello new
	repository: 'github://SabineMa/FixedDecimal/repository';	
	baseline: 'FixedDecimal';
	load.
```

But when I try to load within my baseline, like this:

`spec baseline: 'FixedDecimal' with: [ spec repository: 'github://hernanmd/FixedDecimal/repository' ]`
or
`spec baseline: 'FixedDecimal' with: [ spec repository: 'github://SabineMa/FixedDecimal/repository' ]`

then only my version works and I assume that the reason is that in the baseline you refer to your GitHub repo. But this does not exist. So, if I remove it, like in my fork, it works. I also had look in other repos and saw that there is no such line.

So, if you would accept it, could you please move the tag or create a new one?

**Comment by hernanmd** [comment]
Hi Sabine,

I did a quick test but couldn't reproduce in a clean Pharo 6.1 image. Would you mind to test it with the attached .st?

[BaselineOfFDTest.zip](https://github.com/hernanmd/FixedDecimal/files/2704048/BaselineOfFDTest.zip)

Load the .st with the file browser and then evaluate: 

```smalltalk
BaselineOfFDTest project latestVersion load
```

I ran the test, only one failing (testAdoption) but I think is unrelated to your load problem.
Can you paste the errors if any?

**Comment by SabineMa** [comment]
Hi Hernan,
your example works. I have to investigate where the problem comes from. I will come back to you after Christmas. Have a nice time.
Sabine

**Comment by SabineMa** [comment]
The only thing I can say that if I do not change anything but change between your repo and mine in my baseline
`spec baseline: 'FixedDecimal' with: [ spec repository: 'github://hernanmd/FixedDecimal/repository' ]`
vs
`spec baseline: 'FixedDecimal' with: [ spec repository: 'github://SabineMa/FixedDecimal/repository' ]
`
then with my repo it works and with yours it does not.

Perhaps I have to tell you that I create a clone and then load from the clone, all in a docker image. 
This is the error: 
bildschirmfoto 2018-12-21 um 23 12 34

**Comment by hernanmd** [comment]
It's hard to tell without being able to reproduce all steps. For one side I would check to pull and run a clean container (not cached layer, remove existing images like docker image rm <image id> , etc).

Another thing is you could discard this particular README.md edit and I will integrate your additional changes in the PR. Let me know.

**Comment by SabineMa** [comment]
Hi Hernan,

all the steps are done automatically by our CI and everything is fresh/new and in a clean container. The pharo image and all the code is retrieved new when building it.

I do not know how to remove the README and I don't see it in the pull request: 

bildschirmfoto 2018-12-22 um 19 24 20

Perhaps I don't understand you correctly. 

If you could create a tagged version of Fixed decimal with the changes in the pull request, it would be great. It seems that there is no disadvantage if you remove the link to the repository. Then we could load it. Otherwise I can also load my fork.

I can also try to create an example after holidays to reproduce it from a fresh image for you. Currently it is noch possible 🎄 

Thank you for your time and your work!

**Comment by SabineMa** [comment]
I had a look at other repos e.g.
https://github.com/noha/pharo-toolbox/blob/master/source/BaselineOfExceptionReport.package/BaselineOfExceptionReport.class/instance/baseline..st

**Comment by SabineMa** [comment]
I had al look in other small repository baselines like this
https://github.com/noha/pharo-toolbox/blob/master/source/BaselineOfExceptionReport.package/BaselineOfExceptionReport.class/instance/baseline..st
or
https://github.com/pharo-contributions/OrderPreservingDictionary/blob/master/src/BaselineOfOrderPreservingDictionary/BaselineOfOrderPreservingDictionary.class.st
or
https://github.com/pharo-contributions/Artefact/blob/development/src/BaselineOfArtefact/BaselineOfArtefact.class.st

and I don't see that it is needed that the repository points back to itself
https://github.com/pharo-tips-and-tricks/pharo-tips-and-tricks/blob/master/General/Baselines.md

But it can absolutely be that I don't understand correctly!

**Comment by hernanmd** [comment]
Hi Sabine,

Actually the baseline.st change is fine, the issue with the repository point back to itself is probably I was learning how to make Baselines and just copied from other BaselineOf. 

So the only change I propose you to make is to revert back your README.md file so I don't integrate it in my README.md with your name. You could just then commit again and PR.

**Comment by SabineMa** [comment]
Hi Hernan, 
can you please tag it after merge? 
Thank you and merry Christmas
Sabine

**Pull request closed without merging**
